import Head from "next/head";
import { FormEvent, useCallback, useState } from "react";
import styles from "../styles/Home.module.css";
import { PermittedPayload } from "./api/generate";

export default function Home() {
  const [result, setResult] = useState<string>();

  const fetchImage = useCallback(async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const body = JSON.stringify({} as PermittedPayload);

    const res = await fetch("/api/generate", {
      method: "post",
      body,
    });
    setResult(await res.text());
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form onSubmit={fetchImage}>
        <input type="submit" />
      </form>

      {result && <img className={styles.img} id="result" src={result} />}
    </div>
  );
}
